apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: yatest
  name: pvc-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linode-block-storage